CREATE TABLE BRANCH(
 BNAME VARCHAR(50),
 CITY VARCHAR(50)
 )

 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('VRCE','NAGPUR')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('AJNI','NAGPUR')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('KAROLBAGH','DELHI')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('CHANDI','DELHI')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('DHARAMPETH','NAGPUR')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('ANDHERI','BOMBAY')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('VIRAR','BOMBAY')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('NEHRU PLACE','DELHI')

 
 INSERT INTO BRANCH (BNAME,CITY)
 VALUES
 ('POWAI','BOMBAY')
