USE CSE_3B_313

--PART A
ALTER TABLE DEPOSIT 
ADD CITY VARCHAR(20),PINCODE INT

ALTER TABLE DEPOSIT 
ALTER COLUMN CNAME VARCHAR(35)

ALTER TABLE DEPOSIT
ALTER COLUMN AMOUNT INT

EXEC SP_RENAME 'DEPOSIT.ACTNO','ANO'

ALTER TABLE DEPOSIT
DROP COLUMN CITY

EXEC SP_RENAME 'DEPOSIT','DEPOSIT_DETAIL'

--PART B

EXEC SP_RENAME 'DEPOSIT_DETAIL.ADATE','AOPENDATE'

ALTER TABLE DEPOSIT_DETAIL
DROP COLUMN AOPENDATE

EXEC SP_RENAME 'DEPOSIT_DETAIL.CNAME','CustomerName'

--PART C

CREATE TABLE STUDENT_DETAIL
(
  Enrollment_No VARCHAR(20),
  Name VARCHAR(25),
  CPI DECIMAL(5,2),
  Birthdate DATETIME
)

ALTER TABLE STUDENT_DETAIL
ADD City VARCHAR(20) NOT NULL,Backlog INT NULL

ALTER TABLE STUDENT_DETAIL
ALTER COLUMN Name VARCHAR(35)

ALTER TABLE STUDENT_DETAIL
ALTER COLUMN CPI INT 

EXEC SP_RENAME 'STUDENT_DETAIL.Enrollment_No','ENO'

ALTER TABLE STUDENT_DETAIL
DROP COLUMN City

EXEC SP_RENAME 'STUDENT_DETAIL','STUDENT_MASTER'