USE CSE_3B_313


--PART-B--
CREATE TABLE EMPLOYEE
(
  NAME VARCHAR(50),
  CITY VARCHAR(50),
  AGE INT
)

INSERT INTO EMPLOYEE
VALUES
('JAY PATEL','RAJKOT',30),
('RAHUL DAVE','BARODA',35),
('JEET PATEL','SURAT',31),
('VIJAY RAVAL','RAJKOT',30)

SELECT * INTO EMPLOYEE_DETAIL FROM EMPLOYEE

SELECT NAME,CITY INTO EMPLOYEE_DATA FROM EMPLOYEE
WHERE 1=0

SELECT * INTO EMPLOYEE_INFO FROM EMPLOYEE
WHERE 1=3


--PART-C--
INSERT INTO EMPLOYEE_INFO
SELECT * FROM EMPLOYEE 
WHERE CITY='RAJKOT'

INSERT INTO EMPLOYEE_INFO
SELECT * FROM EMPLOYEE 
WHERE AGE>32