USE CSE_3B_313

CREATE TABLE CRICKET
(
  NAME VARCHAR(50),
  CITY VARCHAR (50),
  AGE INT
)

INSERT INTO CRICKET
VALUES
('SACHIN TENDULKAR','MUMBAI',30),
('RAHUL DRAVID', 'BOMBAY',35),
('M.S.DHONI', 'KHARKHAND',31),
('SURESH RAINA', 'GUJARAT',30)

SELECT * INTO WORLDCUP FROM CRICKET

SELECT NAME,CITY INTO T20 FROM CRICKET
WHERE 1=0

SELECT * INTO IPL FROM CRICKET
WHERE 1=2